### ISSUE TITLE
Not able to determine the correct notes for each hand

### ISSUE THREAD

**Issue by gaurpulkit** [captnfab/PianoBooster#293]
After running various .mid files, I noticed that in some of them it shows that the notes which were supposed to be of the right hand part are not correctly recognized and it leads to a lot of issues when you try to play only one hand with your piano because then you have to play the wrong notes to get it to move forward in "Follow You" mode. This is also a problem when I tried to play some of the left hand notes with my midi keyboard, it just jumped from F clef to G clef and I wasn't able to play the notes in between at all.

**Comment by louis-barman** [comment]
@Zuj3brusu Do you please have the version number of piano booster that you are using? and can you also please post an example MIDI file that shows the problem?

**Comment by gaurpulkit** [comment]
@louis-barman I am using Version 1.0.0 and one example of the midi file that is showing this error can be downloaded from https://musescore.com/user/2146376/scores/2184946

**Comment by louis-barman** [comment]
@Zuj3brusu Wow that is a hard piece. I could only manage it by setting the speed to 60% and even then playing it very slowly a single hand at a time. But I did not find any problem with playing through either hand. 

I am trying to guess what your issue  is -- You wrote `have to play the wrong notes to get it to move forward` have you tried turning on courtesy accidentals in the PB settings. As a single accidental or natural applies to the whole bar.

Also another guess (but not in this piece) some times Musescore might use more than  two MIDI tracks for each hand for example when there are multiple voices played in one hand. And also maybe when Musescore swaps from the base to the treble clef. PB will only work if there is a slinge track for each hand. If a hand uses more than a single track you will need to merge them together to work with PB.

Another thing to eliminate --  please confirm you hit the problem when **downloading the MIDI file** (rather than downloading the MuseScore file) from that link you provided. Just eliminating the way you exported the MIDI file musescore.

What os are you on?

For me to be able to reproduce the problem you need to provide the MIDI file AND a screenshot circling the point it fails.

**Comment by gaurpulkit** [comment]
@louis-barman Yes, I am downloading the MIDI file (.mid) and I am on Windows 10. This is the exact midi file that is showing the error. I am unable to attach a screenshot here but I am not able to play the third note on the treble clef. First note is G, second is D and the next note is supposed to be B but it is shown as a darkened note in PB and is skipped when using "Follow You". I did try the courtesy accidentals thing but it didn't have any effect.

**Comment by louis-barman** [comment]
It sound like you have restricted the notes that you play. please go to menu -> Settings -> Piano Keyboards settings as shown in the screen shot below. 
![image](https://user-images.githubusercontent.com/5164566/113609440-ad55f900-9643-11eb-9127-520bf58333e2.png)
The lowest note should be 0 and the highest 127 Also go to Settings -> Midi settings and check the Midi input Device matches your keyboard if it say None (PC keyboard) it will also cause the effect that you are getting.

It is easy to add screenshots just click on the help prompt that says "attach files by dragging & dropping".

Please let me know if that fixes the problem.

**Comment by gaurpulkit** [comment]
Hey. I checked and I'm like 101% sure that it was not doing this before and I faced the error, but when I checked this Piano keyboard setting right now, it is somehow working absolutely fine. I don't know why it caused the error before. Thanks for the help.
